export const FETCH_PRODUCTS_DETAILS_REQUEST = 'FETCH_PRODUCTS_DETAILS_REQUEST';
export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_ERROR = 'FETCH_PRODUCTS_DETAILS_ERROR';
